[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = ["hardhat/=node_modules/hardhat/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config